### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#7]
### Description:
Create a style guide for MozFest's visual direction for 2017. Last year's guide and the new Mozilla branding will help inform this.

### Dependencies: 
- [x] #4 Visual Direction Moodboard
- [x] #5 Mozilla Festival Lockup 
- [x] #6 Space Icons
- [x] #48 Tagline Lockup
- [x] #49 Colours
- [x] #46 Art Texture and Patterns

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/drive/folders/0B2irLVDJivhLNUJMb3hGN2JIM0U?usp=sharing
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/76#issuecomment-250317084

__________________________
#### Deadline
GanttStart: 2017-08-02
GanttDue: 2017-08-22

**Comment by sabrinang** [comment]
I'll be developing and documenting established design assets in the style guide this will be finalized as an up and coming .ai file and an easier to share format via gslides that you can follow. 

WIP Slides

Style Guide (Simplified - for wranglers/session hosts): https://docs.google.com/presentation/d/1E7k4LHwab2QsdUereRBN3ePJvRC0ex2wwJCKBX3jKn4/edit?usp=sharing

Style Guide (Extended - for design contractors/mofo design team): https://docs.google.com/a/mozilla.com/presentation/d/1aGORKRRTzvVXo19XeBYeOZbDA5QkM-X1vCjNMpcj9Vc/edit?usp=sharing

**Comment by sabrinang** [comment]
.ai and .pdf files can be found in gdrive here: https://drive.google.com/open?id=0B4Q8pzCpDS_eSjZ1QTVGM2lRaGM

**Comment by sabrinang** [comment]
![guide](https://user-images.githubusercontent.com/2492510/30132339-e3973920-9304-11e7-9d17-5ef7aca89dce.jpg)
