### ISSUE TITLE
Master Social Media Graphics List 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#8]
### Description
Coordinate with MozFest 2017 social/comms calendar and create social media graphics that accompany written posts on twitter, facebook, instagram etc. to be shared before, during and after MozFest.

Refer to this year's social calendar and start planning 1-2 graphic for each phase/theme. Some examples are:
- [x] Call for Proposals https://github.com/mozilla/mozillafestival.org/issues/541
- [x] Email Headers for 6 Spaces #62 
- [x] 1 min Promotional Video #61 
- [x] Snippet Icons #60
- [x] Opaque Banner/border for Pictures #59  
- [x] Social Gifs + graphic for announcing friday night festival #58 
- [x] Social Gifs + graphic for announcing the live speaker series #57 
- [x] Social templates for quotes/text in same colours scheme as 6 spaces #56
- [x] Social Profile Cards For Each Speaker in Speaker Series #55
- [x] Update various Profile + Cover Photos #19 
- [x] Festival Summary Creative #72 
- [x] Influencer infographic #74 

Other social topics to consider:
- Generic Taglines
- Purchase Tickets
- Promote Festival Features
- Gear up for festival
- Speaker Series
- Festival Weekend
- Post-Festival Recap/Thanks

### Dependencies and Reference Material
- MozFest Social Calendar: https://docs.google.com/spreadsheets/d/18jtXCngRJtcOxu5EFAO5MiAUsWzPpoiAQzt71Gx94SQ/edit#gid=0
- Brief from advocacy: https://docs.google.com/a/mozilla.com/document/d/1iU1KLFgWHFBWWZCzd3KIU5cr09PCtD80kHgDhJ23goM/edit?usp=sharing
- Strategy from advocacy: https://docs.google.com/a/mozilla.com/presentation/d/19VHRoFMKEtlvAya2YQ5PkJY5Au0hbV2Tcuw6vCBgGM0/edit?usp=sharing

### Reference from Previous Years
Previous github issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/84

**Comment by marcwalsh** [comment]
Hey @sabrinang - Are we able to add a refresh of the avatar for Twitter also? Since the chage from square to a circle doesn't sit nicely with last years.

**Comment by sabrinang** [comment]
Good call @marcwalsh, I filed an issue for refreshing profile + cover photos. Will track that progress on issue https://github.com/MozillaFoundation/mozfest-design-2017/issues/19
